### ISSUE TITLE
[Errno 32] Broken pipe

### ISSUE THREAD

**Issue by FeiH36** [SarodYatawatta/federated-pytorch-test#1]
There's an error in running federated_multi.py. 
![ErrorMsg_Snipaste_2021-04-15_17-17-23](https://user-images.githubusercontent.com/33859016/114845648-84d1ba00-9e0e-11eb-8d82-a80c56ddf2be.png)

**Comment by SarodYatawatta** [comment]
It seems you dont have the data files downloaded. The script should first download CIFAR10 data to ./torchdata directory.
Since you are using windows, you need to edit lines 79-81 to replace ./torchdata with the correct location of the data files.
